/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.view;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaCompra extends javax.swing.JFrame {

    /**
     * Creates new form TelaCompra
     */
    public TelaCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTFBUSCAR = new javax.swing.JButton();
        JTFMODELO = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        JTFPRETENSAO = new javax.swing.JComboBox<>();
        JTFVOLTARR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/img/fundocadastro.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(1, 1, 1));

        jLabel3.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Modelo:");

        JTFBUSCAR.setBackground(new java.awt.Color(1, 1, 1));
        JTFBUSCAR.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        JTFBUSCAR.setForeground(new java.awt.Color(254, 254, 254));
        JTFBUSCAR.setText("BUSCAR");
        JTFBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFBUSCARActionPerformed(evt);
            }
        });

        JTFMODELO.setBackground(new java.awt.Color(1, 1, 1));
        JTFMODELO.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        JTFMODELO.setForeground(new java.awt.Color(254, 254, 254));
        JTFMODELO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Duplex", "Mansão", "Apartamento", "Kitnet", "Condomínio", "Cobertura", "Prédio" }));
        JTFMODELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFMODELOActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Pretensão:");

        JTFPRETENSAO.setBackground(new java.awt.Color(1, 1, 1));
        JTFPRETENSAO.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        JTFPRETENSAO.setForeground(new java.awt.Color(254, 254, 254));
        JTFPRETENSAO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Comprar", "Alugar" }));
        JTFPRETENSAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPRETENSAOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(JTFMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(JTFBUSCAR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(JTFPRETENSAO, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFBUSCAR)
                    .addComponent(jLabel3)
                    .addComponent(JTFMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(JTFPRETENSAO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        JTFVOLTARR.setBackground(new java.awt.Color(1, 1, 1));
        JTFVOLTARR.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        JTFVOLTARR.setForeground(new java.awt.Color(254, 254, 254));
        JTFVOLTARR.setText("x");
        JTFVOLTARR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFVOLTARRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JTFVOLTARR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFVOLTARR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 511, 490);

        setBounds(0, 0, 528, 494);
    }// </editor-fold>//GEN-END:initComponents

    private void JTFBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFBUSCARActionPerformed
        if(JTFPRETENSAO.getSelectedItem().equals("Selecione") && JTFMODELO.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(null,"SELECIONE ALGO");
        }
        else{
        if(JTFMODELO.getSelectedItem().equals("Duplex")){
           ExibirDuplex e = new ExibirDuplex();
        e.setVisible(true);
        dispose();
        }
        else if(JTFMODELO.getSelectedItem().equals("Condominio")){
           ExibirCondominio e = new ExibirCondominio();
        e.setVisible(true);
        dispose();
        }
        else if(JTFMODELO.getSelectedItem().equals("Mansão")){
           ExibirMansao e = new ExibirMansao();
        e.setVisible(true);
        dispose();
        }
        else if(JTFMODELO.getSelectedItem().equals("Cobertura")){
           ExibirCobertura e = new ExibirCobertura();
        e.setVisible(true);
        dispose();
        }
        else if(JTFMODELO.getSelectedItem().equals("Kitnet")){
           ExibirKitnet e = new ExibirKitnet();
        e.setVisible(true);
        dispose();
        }
         else if(JTFMODELO.getSelectedItem().equals("Predio")){
           ExibirPredio e = new ExibirPredio();
        e.setVisible(true);
        dispose();
        }
         else if(JTFMODELO.getSelectedItem().equals("Apartamento")){
           ExibirApartamento e = new ExibirApartamento();
        e.setVisible(true);
        dispose();
        }

        
        }
    }//GEN-LAST:event_JTFBUSCARActionPerformed

    private void JTFVOLTARRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFVOLTARRActionPerformed
        CadastroCliente cdc = new CadastroCliente();
        cdc.setVisible(true);
        dispose();
    }//GEN-LAST:event_JTFVOLTARRActionPerformed

    private void JTFMODELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFMODELOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFMODELOActionPerformed

    private void JTFPRETENSAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPRETENSAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPRETENSAOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JTFBUSCAR;
    private javax.swing.JComboBox<String> JTFMODELO;
    private javax.swing.JComboBox<String> JTFPRETENSAO;
    private javax.swing.JButton JTFVOLTARR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
