/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.view;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTFVOLTARR1 = new javax.swing.JButton();
        JTFFINALIZARV = new javax.swing.JButton();
        APT = new javax.swing.JCheckBox();
        MANSAO = new javax.swing.JCheckBox();
        CONDOMINIO = new javax.swing.JCheckBox();
        COBERTURA = new javax.swing.JCheckBox();
        KITNET = new javax.swing.JCheckBox();
        DUPLEX = new javax.swing.JCheckBox();
        PREDIO = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFESTADOV = new javax.swing.JComboBox<>();
        JTFAREA = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JTFPRECOV = new javax.swing.JComboBox<>();
        JTFVOLTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/img/ilgner (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        JTFVOLTARR1.setBackground(new java.awt.Color(1, 1, 1));
        JTFVOLTARR1.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        JTFVOLTARR1.setForeground(new java.awt.Color(254, 254, 254));
        JTFVOLTARR1.setText("x");
        JTFVOLTARR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFVOLTARR1ActionPerformed(evt);
            }
        });

        JTFFINALIZARV.setBackground(new java.awt.Color(1, 1, 1));
        JTFFINALIZARV.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        JTFFINALIZARV.setForeground(new java.awt.Color(254, 254, 254));
        JTFFINALIZARV.setText("FINALIZAR VENDA");
        JTFFINALIZARV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFFINALIZARVActionPerformed(evt);
            }
        });

        APT.setBackground(new java.awt.Color(153, 153, 153));
        APT.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        APT.setForeground(new java.awt.Color(255, 255, 255));
        APT.setText("Apartamento");

        MANSAO.setBackground(new java.awt.Color(153, 153, 153));
        MANSAO.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        MANSAO.setForeground(new java.awt.Color(255, 255, 255));
        MANSAO.setText("Mansão");

        CONDOMINIO.setBackground(new java.awt.Color(153, 153, 153));
        CONDOMINIO.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        CONDOMINIO.setForeground(new java.awt.Color(255, 255, 255));
        CONDOMINIO.setText("Condomínio");
        CONDOMINIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONDOMINIOActionPerformed(evt);
            }
        });

        COBERTURA.setBackground(new java.awt.Color(153, 153, 153));
        COBERTURA.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        COBERTURA.setForeground(new java.awt.Color(255, 255, 255));
        COBERTURA.setText("Cobertura");

        KITNET.setBackground(new java.awt.Color(153, 153, 153));
        KITNET.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        KITNET.setForeground(new java.awt.Color(255, 255, 255));
        KITNET.setText("Kitnet");

        DUPLEX.setBackground(new java.awt.Color(153, 153, 153));
        DUPLEX.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        DUPLEX.setForeground(new java.awt.Color(255, 255, 255));
        DUPLEX.setText("Duplex");

        PREDIO.setBackground(new java.awt.Color(153, 153, 153));
        PREDIO.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        PREDIO.setForeground(new java.awt.Color(255, 255, 255));
        PREDIO.setText("Prédio");

        jLabel3.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Área:");

        jLabel4.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Preço:");

        JTFESTADOV.setBackground(new java.awt.Color(1, 1, 1));
        JTFESTADOV.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        JTFESTADOV.setForeground(new java.awt.Color(254, 254, 254));
        JTFESTADOV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "CE", "RJ", "MG", "PA", "SC", "RN", "BA", "SP", "PE", "ES" }));

        JTFAREA.setBackground(new java.awt.Color(1, 1, 1));
        JTFAREA.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        JTFAREA.setForeground(new java.awt.Color(254, 254, 254));
        JTFAREA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entre 300m² - 600m²", "Entre 600m² - 1.000m²", "Entre 1.000m² - 3.000m²", "Entre 3.000m² - 7.000m²", "Entre 7.000m² - 10.000m²", "Mais de 10.000m²" }));

        jLabel5.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Estado:");

        JTFPRECOV.setBackground(new java.awt.Color(1, 1, 1));
        JTFPRECOV.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        JTFPRECOV.setForeground(new java.awt.Color(254, 254, 254));
        JTFPRECOV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entre R$280 - R$500", "Entre R$500 - R$900", "Entre R$900 - R$1.500", "Entre R$1.500 - R$2.000", "Entre R$2.000 - R$4.000", "Entre R$5.000 - R$8.000", "Entre R$8.000 - R$12.000", "Mais de R$12.000" }));

        JTFVOLTAR.setBackground(new java.awt.Color(1, 1, 1));
        JTFVOLTAR.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        JTFVOLTAR.setForeground(new java.awt.Color(254, 254, 254));
        JTFVOLTAR.setText("x");
        JTFVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFVOLTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(MANSAO, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTFFINALIZARV))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JTFVOLTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(JTFPRECOV, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTFAREA, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFESTADOV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PREDIO, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KITNET, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CONDOMINIO))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(COBERTURA, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(DUPLEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(APT, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFVOLTARR1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTFVOLTARR1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFVOLTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFAREA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JTFPRECOV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFESTADOV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APT)
                    .addComponent(CONDOMINIO)
                    .addComponent(COBERTURA))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PREDIO)
                    .addComponent(KITNET)
                    .addComponent(DUPLEX))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MANSAO)
                    .addComponent(JTFFINALIZARV))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 622, 591);
    }// </editor-fold>//GEN-END:initComponents

    private void JTFVOLTARR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFVOLTARR1ActionPerformed
        TelaCompra tlc = new TelaCompra();
        tlc.setVisible(true);
        dispose();
    }//GEN-LAST:event_JTFVOLTARR1ActionPerformed

    private void CONDOMINIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONDOMINIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONDOMINIOActionPerformed

    private void JTFFINALIZARVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFFINALIZARVActionPerformed
       if(evt.getSource() == JTFFINALIZARV){
           JOptionPane.showMessageDialog(null, "Seu imóvel está a venda!"
                   + "\nObrigado por fazer negócio conosco, a Ilgner Imobiliária agradece!"
                   + "\nEm caso de dúvida ligue para (85)98745-8972"
                   + "\nOu acesse nosso site ilgnerimobiliaria@gmail.com");
       }
    }//GEN-LAST:event_JTFFINALIZARVActionPerformed

    private void JTFVOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFVOLTARActionPerformed
        CadastroFornecedor l = new CadastroFornecedor();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_JTFVOLTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox APT;
    private javax.swing.JCheckBox COBERTURA;
    private javax.swing.JCheckBox CONDOMINIO;
    private javax.swing.JCheckBox DUPLEX;
    private javax.swing.JComboBox<String> JTFAREA;
    private javax.swing.JComboBox<String> JTFESTADOV;
    private javax.swing.JButton JTFFINALIZARV;
    private javax.swing.JComboBox<String> JTFPRECOV;
    private javax.swing.JButton JTFVOLTAR;
    private javax.swing.JButton JTFVOLTARR1;
    private javax.swing.JCheckBox KITNET;
    private javax.swing.JCheckBox MANSAO;
    private javax.swing.JCheckBox PREDIO;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
